# StreamFX Configuration File

# Main application settings
app:
  host: "127.0.0.1"
  port: 8080
  camera: 0

filters:
  face_detection:
    # Overrides the default URL for the face detection inference server.
    ws_url: "ws://127.0.0.1:8000/ws/predict"
    # server_url: "http://127.0.0.1:8000/predict"
  face_blur:
    # Overrides the default URL for the face detection inference server.
    server_url: "http://127.0.0.1:8000/predict"
  face_emoji:
    # Overrides the default URL for the face detection inference server.
    ws_url: "ws://127.0.0.1:8000/ws/predict"
    emoji_folder_path: "face_emojis"